/*
  FireSentinel — ESP32 Firmware
  ------------------------------------------------------
  Reads: flame sensor (analog), MQ-2 smoke/gas sensor (analog),
         DHT22 temperature & humidity.
  Runs a lightweight on-device Decision Tree for an instant local
  alert (buzzer/LED), independent of WiFi/cloud.
  Publishes readings + prediction over MQTT, and logs to ThingSpeak.

  Libraries needed (Arduino IDE > Tools > Manage Libraries):
    - PubSubClient      (MQTT)
    - DHT sensor library (Adafruit)
    - Adafruit Unified Sensor
    - ThingSpeak         (by MathWorks)

  Wiring (adjust pins to your board):
    Flame sensor  AO -> GPIO 34 (ADC1_CH6)
    MQ-2 sensor   AO -> GPIO 35 (ADC1_CH7)
    DHT22 data    -> GPIO 4  (with 10k pull-up to 3.3V)
    Buzzer        -> GPIO 15
    Status LED    -> GPIO 2 (onboard LED on most ESP32 dev boards)
*/

#include <WiFi.h>
#include <PubSubClient.h>
#include <DHT.h>
#include <ThingSpeak.h>
#include "decision_tree.h"   // auto-generated by train_models.py

// ---------------- CONFIG ----------------
const char* WIFI_SSID     = "YOUR_WIFI_SSID";
const char* WIFI_PASSWORD = "YOUR_WIFI_PASSWORD";

// MQTT (e.g. free HiveMQ Cloud broker, or your own Mosquitto broker)
const char* MQTT_BROKER   = "YOUR_BROKER_ADDRESS";   // e.g. xxxx.s1.eu.hivemq.cloud
const int   MQTT_PORT     = 8883;                     // 8883 = TLS, 1883 = plain
const char* MQTT_USER     = "YOUR_MQTT_USERNAME";
const char* MQTT_PASS     = "YOUR_MQTT_PASSWORD";
const char* MQTT_TOPIC    = "firesentinel/sensors";
const char* MQTT_CLIENT_ID = "firesentinel-esp32-01";

// ThingSpeak
unsigned long TS_CHANNEL_ID = 0000000;          // your channel ID
const char*   TS_WRITE_API_KEY = "YOUR_TS_KEY";

// Pins
#define FLAME_PIN   34
#define MQ2_PIN     35
#define DHT_PIN     4
#define BUZZER_PIN  15
#define LED_PIN     2

#define DHT_TYPE DHT22

// ---------------- GLOBALS ----------------
WiFiClient wifiClient;        // use WiFiClientSecure for TLS/MQTTS
PubSubClient mqttClient(wifiClient);
DHT dht(DHT_PIN, DHT_TYPE);

const unsigned long READ_INTERVAL_MS = 5000;   // publish every 5s
unsigned long lastReadTime = 0;

// ---------------- WIFI ----------------
void connectWiFi() {
  Serial.print("Connecting to WiFi");
  WiFi.begin(WIFI_SSID, WIFI_PASSWORD);
  while (WiFi.status() != WL_CONNECTED) {
    delay(500);
    Serial.print(".");
  }
  Serial.println("\nWiFi connected. IP: " + WiFi.localIP().toString());
}

// ---------------- MQTT ----------------
void connectMQTT() {
  mqttClient.setServer(MQTT_BROKER, MQTT_PORT);
  while (!mqttClient.connected()) {
    Serial.println("Connecting to MQTT broker...");
    if (mqttClient.connect(MQTT_CLIENT_ID, MQTT_USER, MQTT_PASS)) {
      Serial.println("MQTT connected.");
    } else {
      Serial.print("MQTT connect failed, rc=");
      Serial.print(mqttClient.state());
      Serial.println(" retrying in 3s");
      delay(3000);
    }
  }
}

// ---------------- LOCAL ALERT ----------------
void triggerLocalAlert(int status) {
  // status: 0 = Normal, 1 = Warning, 2 = Fire
  switch (status) {
    case 0:
      digitalWrite(LED_PIN, LOW);
      digitalWrite(BUZZER_PIN, LOW);
      break;
    case 1:
      digitalWrite(LED_PIN, HIGH);
      digitalWrite(BUZZER_PIN, LOW);   // LED only, no siren yet
      break;
    case 2:
      digitalWrite(LED_PIN, HIGH);
      digitalWrite(BUZZER_PIN, HIGH);  // full alarm
      break;
  }
}

const char* statusLabel(int status) {
  if (status == 0) return "Normal";
  if (status == 1) return "Warning";
  return "Fire";
}

// ---------------- SETUP ----------------
void setup() {
  Serial.begin(115200);
  pinMode(BUZZER_PIN, OUTPUT);
  pinMode(LED_PIN, OUTPUT);

  dht.begin();
  connectWiFi();
  connectMQTT();
  ThingSpeak.begin(wifiClient);
}

// ---------------- MAIN LOOP ----------------
void loop() {
  if (!mqttClient.connected()) connectMQTT();
  mqttClient.loop();

  unsigned long now = millis();
  if (now - lastReadTime < READ_INTERVAL_MS) return;
  lastReadTime = now;

  // ---- Read sensors ----
  int flameRaw = analogRead(FLAME_PIN);       // 0-4095
  int smokeRaw = analogRead(MQ2_PIN);         // 0-4095, convert to approx ppm below
  float temperature = dht.readTemperature();  // Celsius
  float humidity = dht.readHumidity();

  if (isnan(temperature) || isnan(humidity)) {
    Serial.println("DHT22 read failed, skipping this cycle.");
    return;
  }

  // Rough ADC -> ppm conversion for MQ-2; calibrate against your specific
  // sensor + a known reference gas source for accurate values.
  float smokePPM = map(smokeRaw, 0, 4095, 0, 10000);

  // ---- On-device prediction (instant, no network dependency) ----
  int localStatus = predictFireStatus(flameRaw, smokePPM, temperature, humidity);
  triggerLocalAlert(localStatus);

  Serial.printf("Flame:%d Smoke:%.0fppm Temp:%.1fC Hum:%.1f%% -> %s\n",
                flameRaw, smokePPM, temperature, humidity, statusLabel(localStatus));

  // ---- Publish to MQTT (backend runs the heavier Random Forest on this) ----
  char payload[200];
  snprintf(payload, sizeof(payload),
    "{\"flame_value\":%d,\"smoke_ppm\":%.1f,\"temperature_c\":%.1f,\"humidity_pct\":%.1f,\"local_status\":%d}",
    flameRaw, smokePPM, temperature, humidity, localStatus);

  // NOTE: PubSubClient's publish() only supports QoS 0 (fire-and-forget).
  // True QoS 1 (at-least-once delivery) on ESP32 would require either a
  // different MQTT library (e.g. esp-mqtt) or manually implementing
  // acknowledgment tracking. Left as QoS 0 here as a known limitation --
  // the backend and simulator use QoS 1 since they don't have this constraint.
  mqttClient.publish(MQTT_TOPIC, payload);

  // ---- Log to ThingSpeak (cloud backup + built-in charts) ----
  ThingSpeak.setField(1, flameRaw);
  ThingSpeak.setField(2, smokePPM);
  ThingSpeak.setField(3, temperature);
  ThingSpeak.setField(4, humidity);
  ThingSpeak.setField(5, localStatus);
  ThingSpeak.writeFields(TS_CHANNEL_ID, TS_WRITE_API_KEY);
}